### ISSUE TITLE
老哥 这个图表库有没有文档参考？

### ISSUE THREAD

**Issue by sinksmell** [wuxiaoxiaoshen/gocharts#1]
RT 打破0 star

**Comment by XieWeiXie** [comment]
> RT 打破0 star

没写完还。

**Comment by sinksmell** [comment]
> > RT 打破0 star
> 
> 没写完还。

我想参与这个库的开发,不知道可以吗?

**Comment by XieWeiXie** [comment]
> > > RT 打破0 star
> > 
> > 
> > 没写完还。
> 
> 我想参与这个库的开发,不知道可以吗?

欢迎 PR
